name: Copilot Metrics Archiver
description:
  A GitHub Action that retrieves GitHub Copilot usage metrics from the API and
  organizes them into daily JSON files and generate an adoption report.
author: Francois Gerthoffert

branding:
  icon: activity
  color: green

# Define your inputs here.
inputs:
  github_token:
    description: GitHub token with read access to the project and its issues/PRs
    required: true
  github_org:
    description: GitHub organization to fetch Copilot metrics for
    required: true
  path:
    description:
      Local path where previous JSON files are stored and where new ones. If
      none provided, a temporary directory will be used and passed as output.
    default: ''
    required: false
  summary_report:
    description:
      Set to 'true' to generate a summary report in the GitHub Actions job
      summary.
    default: 'false'
    required: false
  metrics:
    description: >-
      Comma-separated list of report types to collect. Valid values:
      organization, users, all. Each report type is stored in its own subfolder.
    default: 'all'
    required: false
  lookback_days:
    description: Number of days to look back in history for missing data.
    default: '100'
    required: false

# Define your outputs here.
outputs:
  path:
    description:
      The path where JSON files are stored or a temporary directory if none was
      provided.

runs:
  using: node24
  main: dist/index.js
